version: '3.8'
services:
  tickets-db:
    build:
      context: .
      dockerfile: Dockerfile.sqlserver
    container_name: tickets-db
    environment:
      SA_PASSWORD: "Pruebas123*"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Pruebas123*' -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  tickets-app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://tickets-db:1433;databaseName=master;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: Pruebas123*
    depends_on:
      tickets-db:
        condition: service_healthy

volumes:
  sqlserver-data:
